!!python/object/new:moveit_msgs.msg._RobotTrajectory.RobotTrajectory {state: [!!python/object/new:trajectory_msgs.msg._JointTrajectory.JointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, world]}, [ur5_shoulder_pan_joint, ur5_shoulder_lift_joint,
          ur5_elbow_joint, ur5_wrist_1_joint, ur5_wrist_2_joint, ur5_wrist_3_joint],
        [!!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [3.141525367335502, -0.8551284899591112, 1.0994846175806376,
                -1.8151618714140492, -1.570737823094337, 5.97148080689891e-05], !!python/tuple [
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [-0.13993745233551785,
                0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 0]}]}, !!python/object/new:trajectory_msgs.msg._JointTrajectoryPoint.JointTrajectoryPoint {
            state: [!!python/tuple [3.141497272739317, -0.8551260211495254, 1.0996050502589685,
                -1.8151856356061762, -1.5708147091029234, 7.38596681971103e-05], !!python/tuple [
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0], !!python/tuple [0.13993745233551785,
                -0.012296988412227703, -0.5998677493910398, 0.11836797657335042, 0.3829644708533507,
                -0.07045467665510122], !!python/tuple [], !!python/object/new:genpy.rostime.Duration {
                state: [0, 20038233]}]}]]}, !!python/object/new:trajectory_msgs.msg._MultiDOFJointTrajectory.MultiDOFJointTrajectory {
      state: [!!python/object/new:std_msgs.msg._Header.Header {state: [0, !!python/object/new:genpy.rostime.Time {
              state: [0, 0]}, '']}, [], []]}]}
